//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Course
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int id { get; set; }
        public int room { get; set; }
        public string state { get; set; }
        public string groupName { get; set; }
        public string teacher { get; set; }
        public byte @class { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<byte> day { get; set; }
    
        public virtual Rooms Rooms { get; set; }
    }
}
